-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(F.SALES_AMOUNT) * P.PRICE AS SALES
FROM PRODUCT AS P
INNER JOIN OFFLINE_SALE AS F
ON P.PRODUCT_ID = F.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE