-- 코드를 입력하세요
WITH CAR_TOTAL_RENTAL_COUNT AS (
    SELECT CAR_ID, COUNT(*) AS TOTAL_RENTALS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID 
    HAVING COUNT(*) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
AND CAR_ID IN (SELECT CAR_ID FROM CAR_TOTAL_RENTAL_COUNT)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;